require_relative '../node_modules/react-native/scripts/react_native_pods'
require_relative '../node_modules/@react-native-community/cli-platform-ios/native_modules'

platform :ios, '10.0'

project 'lezzoo',
'Debug' => :debug,
'Release' => :release,
'Dev.Debug' => :debug,
'Dev.Release' => :release,
'Staging.Debug' => :debug,
'Staging.Release' => :release,
'Prod.Debug' => :debug,
'Prod.Release' => :release

target 'lezzoo' do

  pod 'react-native-config', :path => '../node_modules/react-native-config'

  target 'lezzooTests' do
    inherit! :complete
    # Pods for testing
  end

  config = use_native_modules!
  use_react_native!(:path => config["reactNativePath"])
  # Enables Flipper.
  #
  # Note that if you have use_frameworks! enabled, Flipper will not work and
  # you should disable these next few lines.
  use_flipper!
  post_install do |installer|
    flipper_post_install(installer)
  end
end

target 'lezzoo-tvOS' do
  # Pods for lezzoo-tvOS

  target 'lezzoo-tvOSTests' do
    inherit! :search_paths
    # Pods for testing
  end

end
