require_relative '../node_modules/react-native/scripts/react_native_pods'
require_relative '../node_modules/@react-native-community/cli-platform-ios/native_modules'

platform :ios, min_ios_version_supported
prepare_react_native_project!
flipper_config = ENV['NO_FLIPPER'] == "1" ? FlipperConfiguration.disabled : FlipperConfiguration.enabled
linkage = ENV['USE_FRAMEWORKS']
if linkage != nil
 Pod::UI.puts "Configuring Pod with #{linkage}ally linked Frameworks".green
 use_frameworks! :linkage => linkage.to_sym
end

install! 'cocoapods', :deterministic_uuids => false

  # Flags change depending on the env values.
  flags = get_default_flags()

project 'lezzoo',
'Debug' => :debug,
'Release' => :release,
'Dev.Debug' => :debug,
'Dev.Release' => :release,
'Staging.Debug' => :debug,
'Staging.Release' => :release,
'Prod.Debug' => :debug,
'Prod.Release' => :release

target 'lezzoo' do

  pod 'react-native-config', :path => '../node_modules/react-native-config'

  target 'lezzooTests' do
    inherit! :complete
    # Pods for testing
  end

  config = use_native_modules!
    use_react_native!(
      :path => config[:reactNativePath],
       # Hermes is now enabled by default. Disable by setting this flag to false.
        # Upcoming versions of React Native may rely on get_default_flags(), but
        # we make it explicit here to aid in the React Native upgrade process.
      :hermes_enabled => flags[:hermes_enabled],
      :fabric_enabled => flags[:fabric_enabled],
      # Enables Flipper.
      #
      # Note that if you have use_frameworks! enabled, Flipper will not work and
      # you should disable the next line.
      :flipper_configuration => FlipperConfiguration.enabled(["Debug", "Dev.Debug", "Staging.Debug", "Prod.Debug"]),
      # An absolute path to your application root.
      :app_path => "#{Pod::Config.instance.installation_root}/.."
    )

  post_install do |installer|
    react_native_post_install(
      installer,
      # Set `mac_catalyst_enabled` to `true` in order to apply patches
      # necessary for Mac Catalyst builds
      :mac_catalyst_enabled => false
    )
     __apply_Xcode_12_5_M1_post_install_workaround(installer)
  end

end
